import sys
sys.path.append("/opt/anaconda3/lib/python3.9/site-packages")

import streamlit as st
from PIL import Image

def show_article_page():
    page = st.sidebar.selectbox("Select", ("Article 1", "Article 2", "Article 3", "Article 4"))

    if page == "Article 2":
        st.header("Article 2 - SUICIDE PREVENTION")
        image = Image.open("stopsui.jpg")
        st.image(image, width=500)

        st.subheader("Key details")
        st.markdown("Every year, around 700,000 people commit suicide. There are considerably more suicide attempts than suicides. The single biggest risk factor for suicide in the general population is having attempted suicide before. Among people aged 15 to 29, suicide is the fourth most common cause of death. In low- and middle-income countries, suicide rates are 77% higher. The three most prevalent means of suicide worldwide are hanging, ingesting pesticides, and firearms.")
        st.subheader("Methods of suicide")
        st.markdown("Pesticide self-poisoning is estimated to be the cause of 20% of suicides worldwide, the most of which occur in rural agricultural areas of low- and middle-income nations. Hanging and firearms are additional prevalent suicide methods. According to LIVE LIFE: An Implementation Guide for Suicide Prevention in Countries, it is crucial to understand the most prevalent suicide techniques in order to develop prevention strategies that have been proven to be successful, such as restricting access to suicide methods.")
        image = Image.open("reasons_of_suicide.jpg")
        st.image(image, width=500)

        st.subheader("Prevention and Control")
        st.markdown("Suicides can be prevented. Numerous actions can be taken to stop suicide and suicide attempts at the community, subpopulation, and individual levels. The WHO's LIVE LIFE suicide prevention strategy suggests the following significant, productive evidence-based interventions: Adolescents' socio-emotional life skills should be promoted, and early identification, assessment, management, and follow-up of anyone affected by suicidal behaviour should be undertaken., Limit access to the means of suicide (such as pesticides, firearms, and certain pharmaceuticals); engage with the media for responsible reporting of suicide; These need to work hand in hand with the following fundamental pillars: situation analysis, cross-sectoral cooperation, awareness-raising, capacity building, finance, surveillance, and monitoring and evaluation. Multiple societal sectors, including the health sector as well as others like education, labour, agriculture, business, justice, law, defence, politics, and the media, must coordinate and work together to prevent suicide. Since suicide is a complex issue, these efforts must be comprehensive and interconnected.")
        st.subheader("Challenges and obstacles")
        st.markdown("Taboo and stigma: Stigma, particularly surrounding mental disorders and suicide, means many people thinking of taking their own life or who tried to commit suicide are not seeking help and are therefore not receiving the help they need. Due to a lack of awareness of suicide as a serious public health issue and the stigma of discussing it openly in many communities, the prevention of suicide has not received appropriate attention. Only 38 nations report having a national suicide prevention policy, and only a few of nations have made suicide prevention one of their top health objectives. For nations to advance in suicide prevention, community awareness-raising and taboo-busting are essential.")
        st.subheader("Data Quality")
        st.markdown("The quality and quantity of statistics on suicide and suicide attempts are both lacking globally. Only 80 of the Member States have reliable vital registry data that can be utilised for estimating suicide rates directly. This problem of poor-quality mortality data is not distinct to suicide, but given the sensitivity of suicide – and the illegality of suicidal behaviour in some countries – it is likely that insufficient reporting and misclassification are more prevalent for suicide than for most other causes of death.   Effective suicide prevention measures necessitate increased surveillance and monitoring of suicide and suicide attempts. The need for each nation to enhance the comprehensiveness, accuracy, and timeliness of its data on suicide is highlighted by cross-national disparities in suicide trends as well as changes in suicide rates, features, and methods. This covers essential suicide registration, hospital-based registers of suicide attempts, and nationally representative surveys gathering data on self-reported suicide attempts.")

    elif page == "Article 3":
        st.header("Article 3 - SUICIDE PREVENTION: WHY TALKING ABOUT “IT” IS ESSENTIAL")
        image = Image.open("suicide-prevention-sticky-notes.jpg")
        st.image(image, width=400)

        st.markdown("Suicide touches all of us. Most of us have known or loved at least one person who took their life or who lives in the aftermath of losing a friend or family member to suicide. After cancer and heart disease, suicide accounts for more years of life lost (1.5 million each year) than any other cause of death. However, unlike cancer and heart disease, most of us feel very uncomfortable talking to someone about whether they are having thoughts about harming themselves.")
        st.markdown("Many of us grew up believing people who took their lives were crazy, selfish or morally defective. Medical research has proven suicidal thoughts are usually the result of psychiatric conditions such as depression, anxiety or schizophrenia, but this hasn’t helped us feel more comfortable talking about suicide.")
        st.subheader("Statistics")
        st.write("According to the U.S. Center for Disease Control…")
        st.write("-47,173 Americans died by suicide in 2017")
        st.write("-1.4 million suicide attempts in 2017 (estimated)")
        st.write("-10th leading cause of death in the U.S.")
        st.write("-2nd leading cause of death for ages 10-24")
        st.write("-White men ages 45 to 64 have the highest suicide rate")
        st.subheader("Understanding Suicide")
        st.markdown("People who experience suicidal thoughts often don’t want to die but desperately want to escape unbearable suffering. A suicidal person can’t see any way out of their excruciating pain except through death. Despite their desire for the pain to stop, they are deeply conflicted about the act of suicide and wish there was an alternative. Most people who die by suicide talk about ending their lives prior to taking action. Thus, any mention of suicidal thoughts or plans should be taken seriously.")
        st.subheader("Tips for Talking about Suicide")
        st.markdown("Suicide prevention starts with recognizing these warning signs and taking them seriously. However, talking to someone about these signs or symptoms can be extremely difficult. If you are unsure whether someone is suicidal, the best way to find out is to ask. You cannot make a person suicidal by showing you care. In fact, giving a suicidal person the opportunity to express their feelings can provide relief from loneliness and pent-up negative feelings and may prevent a suicide attempt.")
        st.subheader("Getting Help")
        image = Image.open("suicide_prevention.jpg")
        st.image(image, width=700)

        st.markdown("It can be scary to know someone you care about is thinking of ending their life. However, many resources exist to help. Contact the National Suicide Prevention Lifeline 1-800-273-TALK (8255) to talk and obtain resources in your area. If someone shares they are feeling like ending their life, take them to a doctor, local hospital emergency room or mental health professional or call 911 to get the immediate help the person needs to stay safe. The important thing is to get help! If we are willing to ask uncomfortable questions and have difficult conversations, fewer people in our lives will die by suicide.")

    elif page == "Article 4":
        st.header("Article 4 - Suicide Prevention: An Emerging Priority For Health Care")
        image = Image.open("Suicide_Prevention.png")
        st.image(image, width=700)

        st.subheader("Abstract")
        st.markdown("Suicide is a significant public health problem. It is the tenth leading cause of death in the United States, and the rate has risen in recent years. Many suicide deaths are among people recently seen or currently under care in clinical settings, but suicide prevention has not been a core priority in health care. In recent years, new treatment and management strategies have been developed, tested, and implemented in some organizations, but they are not yet widely used. This article examines the feasibility of improving suicide prevention in health care settings. In particular, we consider Zero Suicide, a model for better identification and treatment of patients at risk for suicide.")
        st.subheader("Introduction")
        st.markdown("Suicide is the tenth leading cause of death in the United States, accounting for more than 40,000 deaths annually. Additionally, there are almost 500,000 emergency department (ED) visits annually as a result of intentional self-harm. Costs for ED visits and hospitalizations associated with self-injury among young adults ages 15–24 in 2010 were estimated at $2.6 billion. There are also personal costs, as many people are deeply affected by suicide loss in their families or among close friends.")
        st.subheader("Recent History Of And Priorities In Suicide Prevention")
        image = Image.open("suicide_rates.jpg")
        st.image(image, width=600)

        st.markdown("The first National Strategy for Suicide Prevention was released by Surgeon General David Satcher in 2001. Before then, the most successful prevention program was a 1990s US Air Force effort. This was a broad population-based approach, emphasizing leadership, community education, improved health care, and surveillance. Results included a 33 percent reduction in suicide between 1996 and 2002, with concomitant reductions in homicide and family violence.")
        st.markdown("The initial 2001 national strategy emphasized public health methods, including increasing awareness, reducing access to lethal means, providing better access to mental health care, and reducing the stigma of seeking such care. Other national efforts include the establishment of a technical assistance center (the Suicide Prevention Resource Center) and a crisis call system (the National Suicide Prevention Lifeline), both funded by SAMHSA. In 2007 the Department of Veterans Affairs established suicide protocols for its facilities and now supports a national hotline for veterans in crisis that has answered nearly two million calls and dispatched emergency services for more than 56,000 veterans (Suicide Prevention Program, Mental Health Services, Department of Veterans Affairs, personal communication, March 2, 2016).")
        st.subheader("Should Health Care Systems And Providers Do More?")
        st.markdown("The concept of health care providers’ playing an ongoing instead of visit-oriented role is as useful for suicide prevention as it is for the management of other chronic health conditions. Many individuals who die by suicide were engaged in care or had recent contact with health providers. About 45 percent of those who died by suicide saw a primary care physician in the thirty days before they died. A model known as the “health care neighborhood,” coined by Erin Fries Taylor and colleagues, is one example of an expanded model of primary care that could reach more people at risk for suicide.")
        st.markdown("Several states have recently linked data on participation in mental health and addiction care with death records; up to a quarter of all those who died by suicide had received publicly funded mental health care in the year or two prior to their death, while on average only 2–3 percent of the population is served in these systems. Suicide risk is greatly elevated for people with major mental illnesses (such as depression, schizophrenia, bipolar illness). However, the state data coupled with the developments we discuss in this article suggest that the rate of suicide among patients receiving mental health services can be greatly reduced.")
        st.subheader("Can Improved Health Care Prevent Suicide?")
        st.markdown("Following the 2001 Institute of Medicine’s Crossing the Quality Chasm report, the Henry Ford Health System, a nonprofit health care system located in Detroit, Michigan, began a robust quality improvement program that included efforts to prevent suicide among its patients. The goal of its Perfect Depression Care initiative was “zero defect” mental health care. Stimulated by the call for fundamental changes to improve patient safety, the Henry Ford Health System used deaths by suicide as one measure. Prevention experts Deborah M. Stone and Alex E. Crosby summarized the approach: “This model relied on suicide assessment for all behavioral health patients…. Strategies included means restriction, provider education, follow-up via phone calls, and peer support services.” “Means restriction” in the context of suicide prevention is efforts to reduce or eliminate means of self-harm. The Henry Ford Health System program reduced the suicide rate among patients receiving behavioral health care from an average of 96 people per 100,000 in 1999–2000 to an average of 24 per 100,000 in 2001–10—a reduction of about 75 percent —signaling that sustained and robust health care improvements might affect suicide rates.")
        st.subheader("Evolving Strategies For Suicide Prevention")
        st.markdown("In 2010 secretary of health and human services Kathleen Sebelius and secretary of defense Robert Gates announced the launch of the National Action Alliance for Suicide Prevention, whose mission was to champion suicide prevention as a national priority, update the national strategy, and catalyze new efforts. Several task forces were initiated to review aspects of suicide prevention. One of the first, the Clinical Care and Intervention Task Force, examined the research on detecting and managing suicidality and considered efforts to reduce suicide in health care settings. The task force concluded that there was strong evidence for successfully detecting and managing suicidality in health care. In addition to looking at the work of the Henry Ford Health System, the task force reviewed results of the National Suicide Prevention Lifeline, which showed that supportive contacts (by phone, text message, or letter) reduced suicide among vulnerable individuals. The task force also reviewed the Central Arizona Programmatic Suicide Deterrent System Project, which emphasized staff training and protocols to address suicide. The Arizona program was not formally evaluated, but internal data showed reductions in suicide among people receiving behavioral health care.")
        st.subheader("The Zero Suicide Approach: Elements And Evidence")
        st.write("The Zero Suicide model comprises seven elements, which are described below:")
        image = Image.open("zero_suicide.png")
        st.image(image, width=300)

        st.subheader("Conclusion")
        st.markdown("There are many challenges to improving screening, assessment, and basic management of suicidality in general medical settings, including primary care. This is where most patients who subsequently die by suicide are seen, so improving detection in these settings, as the Joint Commission has urged, is important. However, behavioral health care within primary care and other general medical settings is in its infancy. Improving payment for integrated behavioral health services, expansion of the patient-centered medical home model, and patients’ preferences for integrated care are likely to increase the integration of care, creating an improved environment for suicide prevention in primary care.")


    else:
        st.header("Article 1 - Suicide and Youth: Risk Factors")

        image = Image.open("youthsuicide.png")
        st.image(image, width=300)

        st.markdown("Suicide occurs more often in older than in younger people, but is still one of the leading causes of death in late childhood and adolescence worldwide. This not only results in a direct loss of many young lives, but also has disruptive psychosocial and adverse socio-economic effects. From the perspective of public mental health, suicide among young people is a main issue to address. Therefore we need good insight in the risk factors contributing to suicidal behavior in youth. This mini review gives a short overview of the most important risk factors for late school-age children and adolescents, as established by scientific research in this domain. Key risk factors found were: mental disorders, previous suicide attempts, specific personality characteristics, genetic loading and family processes in combination with triggering psychosocial stressors, exposure to inspiring models and availability of means of committing suicide. Further unraveling and knowledge of the complex interplay of these factors is highly relevant with regard to the development of effective prevention strategy plans for youth suicide.")
        st.subheader("Introduction")
        st.markdown("Suicide is defined as a fatal self-injurious act with some evidence of intent to die. Worldwide, more than 800,000 people die due to suicide each year. It is estimated that about 1.5 million people will die due to suicide by the year 2020. The suicide mortality rate in 2015 was 10.7 per 100,000, which means about one death every 20 s. Suicide accounts for 1.4% of all deaths, and is the 15th leading cause of death globally. Many more men than women die by suicide. The male-to-female ratio varies between 4 to 1 (Europe and Americas) and 1.5 to 1 (Eastern Meditarranean and Western Pacific region), and is highest in richer countries. These suicide figures are probably still an underestimation of the real cases. Registering a suicide is a complicated process, often involving judicial authorities. Suicide deaths may not be recognized or may be misclassified as an accident or another cause of death. Sometimes suicide is not acknowledged or reported, due to its sensitive nature and the taboo that still surrounds it. Suicide attempts, i.e. non-fatal suicidal behavior, are much more frequent, and are estimated to be about 10–20 times more frequent than actual suicide. The estimated global annual prevalence of self-reported suicide attempts is approximately 3 per 1,000 adults. About 2.5% of the population makes at least one suicide attempt during their lifetime.")
        st.subheader("Risk Factors for Suicide in Youth")
        image = Image.open("youth-chart.jpg")
        st.image(image, width=600)

        st.markdown("The definition of youth in terms of strict age ranges is rather arbitrary and varies by country and over time. Suicide under the age of 5 is hard to find. Most literature (including this mini review) on youth suicide refers to school-age children (7–12 years) and adolescents (13–20 years). These young people are by nature vulnerable to mental health problems, especially during the years of adolescence. This period in life is characterized by movement, changes and transitions from one state into another, in several domains at the same time. Young people have to make decisions about important concrete directions in life, for example school, living situation, peer group etc.")
        st.markdown("In recent decades, several population-based psychological autopsy studies of suicides have been conducted, involving interviews with key informants and examination of records, as well as follow-up studies of people who have attempted suicide, revealing important information about the risk factors for youth suicide. Everyone agrees that numerous factors can contribute to suicide, and that ultimately each suicide is caused by a highly unique, dynamic and complex interplay of genetic, biological, psychological and social factors. Nevertheless, it is possible to identify different types of factors that are clearly associated with an increased risk of youth suicide, so this is highly relevant with regard to prevention.")
        st.subheader("Mental Disorders")
        st.markdown("Most studies agree that suicide is closely linked to mental disorders. About 90% of people who commit suicide have suffered from at least one mental disorder. Mental disorders are found to contribute between 47 and 74% of suicide risk. Affective disorder is the disorder most frequently found in this context. Criteria for depression were found in 50–65% of suicide cases, more often among females than males. Substance abuse, and more specifically alcohol misuse, is also strongly associated with suicide risk, especially in older adolescents and males. Finally, associations have also been found between suicide and anxiety disorders, but it is difficult to assess the influence of mood and substance abuse disorders that are also often present in these cases. In general, the comorbidity of mental disorders substantially increases suicide risk.")
        st.subheader("Previous Suicide Attempts")
        image = Image.open("suicide-rates-among-young-people.png")
        st.image(image, width=700)

        st.markdown("Many studies find a strong link between previous suicide attempts, or a history of self-harm, and suicide. About 25–33% of all cases of suicide were preceded by an earlier suicide attempt, a phenomenon that was more prevalent among boys than girls. Research has shown that boys with a previous suicide attempt have a 30-fold increase in suicide risk compared to boys who have not attempted suicide. Girls with previous suicide attempts have a threefold increase in suicide risk. In prospective studies, it was found that 1–6% of people attempting suicide die by suicide in the first year. The risk of suicide is found to be related mainly to the self-inflicting act as such, and less to the degree of suicidal intention of that act.")
        st.subheader("Personality Characteristics")
        st.markdown("Suicide is associated with impulsivity. Although we know that a suicidal process can take weeks, months or even years, the fatal transition from suicidal ideation and suicide attempts to an actual completed suicide often occurs suddenly, unexpectedly and impulsively, especially among adolescents. Difficulties in managing the various, often strong and mixed emotions and mood fluctuations accompanying the confrontation with new and ever-changing challenges in different domains is another risk factor for youth suicide, probably partly influenced by bio-neurological factors. Young people who committed suicide were also found to have had poorer problem-solving skills than their peers. Their behavior was characterized by a rather passive attitude, waiting for someone else to solve the problem for them, for simple problems as well as for more complex interpersonal problems.")
        st.subheader("Family Factors")
        st.markdown("One of the most important sources of support with addressing the many challenges of youth is the family context in which young people live or have grown up. Several risk factors concerning family structure and processes have been linked to suicide behavior in numerous studies. It is estimated that in 50% of youth suicide cases, family factors are involved. One important factor is a history of mental disorders among direct family members themselves, especially depression and substance abuse. It is not clear whether these disorders directly influence the suicidal behavior of the child, or rather do so indirectly, through mental disorders evoked in the child as a result of this family context. Researchers also found an augmented presence of suicidal behavior among family members of young people who have committed suicide.")
        st.subheader("Conclusion")
        st.markdown("Youth suicide constitutes a major public mental health problem. Young people and especially adolescents are by nature a vulnerable group for mental health problems. While suicide is relatively rare in children, its prevalence increases significantly throughout adolescence. And although youth suicide rates are slightly decreasing within the European region, it still ranks as a leading cause of death among the young worldwide and, as such, it is responsible for a substantial number of premature deaths and a huge amount of pointless suffering and societal loss. Each suicide is the result of a complex dynamic and unique interplay between numerous contributing factors, and individual efforts to predict and prevent suicide tend to fail. On the other hand, our knowledge of risk factors is increasing substantially. Mental disorders, previous suicide attempts, specific personality characteristics, genetic loading and family processes in combination with triggering psychosocial stressors, exposure to inspiring models and availability of means of committing suicide are key risk factors in youth suicide. The only way forward is to reduce these risk factors and strengthen protective factors as much as possible by providing integrated and multi-sector (primary, secondary and tertiary) prevention initiatives.")